/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

// THIS FILE IS AUTOMATICALLY GENERATED FROM GIT LOG BEFORE EACH BUILD.
// DO NOT EDIT MANUALLY. CONVENTIONAL COMMITS ARE PARSED AUTOMATICALLY.

export interface CustomChangelogItem {
  tag: 'feat' | 'fix' | 'perf' | 'chore'
  titleEn: string
  titleZh: string
  descEn: string
  descZh: string
  commitHash?: string
}

export interface CustomReleaseGroup {
  version: string
  upstreamBase: string
  date: string
  items: CustomChangelogItem[]
}

export const CUSTOM_CHANGELOG_DATA: CustomReleaseGroup[] = [
  {
    version: 'v1.0.0-rc.41+custom',
    upstreamBase: 'v1.0.0-rc.41',
    date: '2026-10-03',
    items: [
    {
      "tag": "feat",
      "titleEn": "[system-update] automate changelog generation from git log and establish commit guidelines",
      "titleZh": "[system-update] automate changelog generation from git log and establish commit guidelines",
      "descEn": "Commit: bfc05c5ae by BigYellow12138 on 2026-10-03",
      "descZh": "提交: bfc05c5ae · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "bfc05c5ae"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] update custom changelog to v1.0.0-rc.41+custom with latest deliverables",
      "titleZh": "[system-update] update custom changelog to v1.0.0-rc.41+custom with latest deliverables",
      "descEn": "Commit: 214280bb8 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: 214280bb8 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "214280bb8"
    },
    {
      "tag": "feat",
      "titleEn": "[home] embed official ZCode & CherryStudio setup screenshots with mode switch and lightbox",
      "titleZh": "[home] embed official ZCode & CherryStudio setup screenshots with mode switch and lightbox",
      "descEn": "Commit: 57adf125d by BigYellow12138 on 2026-10-03",
      "descZh": "提交: 57adf125d · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "57adf125d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] use official ZCode icon from z.ai and add to hero supported apps",
      "titleZh": "[home] use official ZCode icon from z.ai and add to hero supported apps",
      "descEn": "Commit: 953f17e7d by BigYellow12138 on 2026-10-03",
      "descZh": "提交: 953f17e7d · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "953f17e7d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] add visual mockup diagram with lightbox zoom for ZCode, CherryStudio, and DSH",
      "titleZh": "[home] add visual mockup diagram with lightbox zoom for ZCode, CherryStudio, and DSH",
      "descEn": "Commit: e942cd6d3 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: e942cd6d3 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "e942cd6d3"
    },
    {
      "tag": "feat",
      "titleEn": "[home] remove Gemini 3.7 Flash and GLM 5.3 Flash from featured models, optimize 6-card grid",
      "titleZh": "[home] remove Gemini 3.7 Flash and GLM 5.3 Flash from featured models, optimize 6-card grid",
      "descEn": "Commit: 9d5f78a62 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: 9d5f78a62 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "9d5f78a62"
    },
    {
      "tag": "fix",
      "titleEn": "[home] fix tokens route to keys and perform extensive ablation of redundant sections",
      "titleZh": "[home] fix tokens route to keys and perform extensive ablation of redundant sections",
      "descEn": "Commit: d34c47f04 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: d34c47f04 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "d34c47f04"
    },
    {
      "tag": "feat",
      "titleEn": "[home] remove external docs, align homepage with relay service, and enhance ZCode guide with accurate origin",
      "titleZh": "[home] remove external docs, align homepage with relay service, and enhance ZCode guide with accurate origin",
      "descEn": "Commit: cc28fbacb by BigYellow12138 on 2026-10-03",
      "descZh": "提交: cc28fbacb · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "cc28fbacb"
    },
    {
      "tag": "fix",
      "titleEn": "[home] fix Grok icon reference in featured models wall",
      "titleZh": "[home] fix Grok icon reference in featured models wall",
      "descEn": "Commit: d9775b769 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: d9775b769 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "d9775b769"
    },
    {
      "tag": "fix",
      "titleEn": "[i18n] fix locale namespace structure and align featured models with platform offerings",
      "titleZh": "[i18n] fix locale namespace structure and align featured models with platform offerings",
      "descEn": "Commit: 9f68e6549 by BigYellow12138 on 2026-10-03",
      "descZh": "提交: 9f68e6549 · 提交者: BigYellow12138 (2026-10-03)",
      "commitHash": "9f68e6549"
    }
],
  },
  {
    version: 'v1.0.0-rc.40+custom',
    upstreamBase: 'v1.0.0-rc.40',
    date: '2026-09-30',
    items: [
      {
        tag: 'feat',
        titleEn: 'Card shop recharge banner and redemption guide',
        titleZh: '钱包充值支持官方发卡网直达横幅与兑换引导',
        descEn: 'Added a responsive, theme-adaptive official card shop recharge banner with direct access button, plus redemption capsules and full 7-locale i18n support.',
        descZh: '在钱包充值页引入主题自适应的发卡网自动充值大横幅与直达购买按钮，增加卡密兑换引导胶囊，适配 7 种语言完整国际化。',
        commitHash: '75d4a0c',
      },
      {
        tag: 'feat',
        titleEn: 'Preset theme aligned to simple-large with 0.5 radius',
        titleZh: '系统出厂默认主题对齐超大字体简约 (simple-large) 与 0.5 圆角',
        descEn: 'Set system default customization to simple-large, sans font, 0.5 radius (md), and system dark/light adaptation; fixed underlying data-theme attribute cascade.',
        descZh: '统一系统默认预设为超大字体简约、Sans 字体、0.5 圆角 (md) 及跟随系统深浅自适应，修复底层主题属性映射，新访客与无痕窗口开箱即用。',
        commitHash: '3fc6f2f',
      },
      {
        tag: 'feat',
        titleEn: 'Official tiered billing expressions and model pricing',
        titleZh: '模型官方阶梯计费 (tiered_expr) 与倍率对齐',
        descEn: 'Aligned gpt-6.1-sol, claude-opus-5-5, claude-opus-5, and claude-sonnet-5 with official tiered billing expressions to accurately calculate cache read/write differentials.',
        descZh: '对齐 gpt-6.1-sol、claude-opus-5-5、claude-opus-5、claude-sonnet-5 官方动态阶梯计费表达式，精准核算 Prompt Caching 读写差价与官方费率。',
        commitHash: '75d4a0c',
      },
    ],
  },
]
