/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

// THIS FILE IS AUTOMATICALLY GENERATED FROM GIT LOG BEFORE EACH BUILD.
// DO NOT EDIT MANUALLY. CONVENTIONAL COMMITS ARE PARSED AUTOMATICALLY.

export interface CustomChangelogItem {
  tag: 'feat' | 'fix' | 'perf' | 'chore'
  titleEn: string
  titleZh: string
  descEn: string
  descZh: string
  commitHash?: string
}

export interface CustomReleaseGroup {
  version: string
  upstreamBase: string
  date: string
  items: CustomChangelogItem[]
}

export const CUSTOM_CHANGELOG_DATA: CustomReleaseGroup[] = [
  {
    version: 'v1.0.0-rc.41+custom',
    upstreamBase: 'v1.0.0-rc.41',
    date: '2026-10-03',
    items: [
    {
      "tag": "chore",
      "titleEn": "[guidelines] 统一 Commit 规范为客观克制中文并更新日志脚本",
      "titleZh": "[guidelines] 统一 Commit 规范为客观克制中文并更新日志脚本",
      "descEn": "Commit: 2e903d88b (2026-10-03)",
      "descZh": "提交: 2e903d88b · 2026-10-03",
      "commitHash": "2e903d88b"
    },
    {
      "tag": "chore",
      "titleEn": "[changelog] 自动同步 Git 提交记录至更新日志",
      "titleZh": "[changelog] 自动同步 Git 提交记录至更新日志",
      "descEn": "Commit: 40767a932 (2026-10-03)",
      "descZh": "提交: 40767a932 · 2026-10-03",
      "commitHash": "40767a932"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] 自动化提取 Git 提交记录生成更新日志并制定提交规范",
      "titleZh": "[system-update] 自动化提取 Git 提交记录生成更新日志并制定提交规范",
      "descEn": "Commit: bfc05c5ae (2026-10-03)",
      "descZh": "提交: bfc05c5ae · 2026-10-03",
      "commitHash": "bfc05c5ae"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] 更新二开更新日志数据",
      "titleZh": "[system-update] 更新二开更新日志数据",
      "descEn": "Commit: 214280bb8 (2026-10-03)",
      "descZh": "提交: 214280bb8 · 2026-10-03",
      "commitHash": "214280bb8"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 接入 ZCode 与 Cherry Studio 官方配置截图及全屏查看",
      "titleZh": "[home] 接入 ZCode 与 Cherry Studio 官方配置截图及全屏查看",
      "descEn": "Commit: 57adf125d (2026-10-03)",
      "descZh": "提交: 57adf125d · 2026-10-03",
      "commitHash": "57adf125d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 使用 ZCode 官方图标并添加到首页支持应用列表",
      "titleZh": "[home] 使用 ZCode 官方图标并添加到首页支持应用列表",
      "descEn": "Commit: 953f17e7d (2026-10-03)",
      "descZh": "提交: 953f17e7d · 2026-10-03",
      "commitHash": "953f17e7d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 添加 ZCode、Cherry Studio 与 DSH 界面配置图解",
      "titleZh": "[home] 添加 ZCode、Cherry Studio 与 DSH 界面配置图解",
      "descEn": "Commit: e942cd6d3 (2026-10-03)",
      "descZh": "提交: e942cd6d3 · 2026-10-03",
      "commitHash": "e942cd6d3"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 调整热门模型展示列表为 6 款主力模型及 3x2 网格",
      "titleZh": "[home] 调整热门模型展示列表为 6 款主力模型及 3x2 网格",
      "descEn": "Commit: 9d5f78a62 (2026-10-03)",
      "descZh": "提交: 9d5f78a62 · 2026-10-03",
      "commitHash": "9d5f78a62"
    },
    {
      "tag": "fix",
      "titleEn": "[home] 修正令牌路由为 /keys 并精简首页冗余模块",
      "titleZh": "[home] 修正令牌路由为 /keys 并精简首页冗余模块",
      "descEn": "Commit: d34c47f04 (2026-10-03)",
      "descZh": "提交: d34c47f04 · 2026-10-03",
      "commitHash": "d34c47f04"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 移除外部文档跳转，聚焦中转服务，自适应端点地址",
      "titleZh": "[home] 移除外部文档跳转，聚焦中转服务，自适应端点地址",
      "descEn": "Commit: cc28fbacb (2026-10-03)",
      "descZh": "提交: cc28fbacb · 2026-10-03",
      "commitHash": "cc28fbacb"
    }
],
  },
  {
    version: 'v1.0.0-rc.40+custom',
    upstreamBase: 'v1.0.0-rc.40',
    date: '2026-09-30',
    items: [
      {
        tag: 'feat',
        titleEn: 'Card shop recharge banner and redemption guide',
        titleZh: '钱包充值支持发卡网横幅与兑换引导',
        descEn: 'Added card shop recharge banner with direct access button and redemption guide.',
        descZh: '在钱包充值页增加发卡网自动充值横幅与直达购买按钮，增加卡密兑换引导胶囊。',
        commitHash: '75d4a0c',
      },
      {
        tag: 'feat',
        titleEn: 'Preset theme aligned to simple-large with 0.5 radius',
        titleZh: '系统出厂默认主题调整为简约大字体与 0.5 圆角',
        descEn: 'Set system default theme to simple-large, sans font, 0.5 radius (md), and auto dark mode.',
        descZh: '系统默认预设调整为超大字体简约、Sans 字体、0.5 圆角 (md) 及跟随系统深浅模式。',
        commitHash: '3fc6f2f',
      },
      {
        tag: 'feat',
        titleEn: 'Official tiered billing expressions and model pricing',
        titleZh: '模型官方阶梯计费与倍率对齐',
        descEn: 'Aligned model pricing expressions with official tiered rates for prompt caching reads and writes.',
        descZh: '对齐常用模型官方动态阶梯计费表达式，核算 Prompt Caching 读写差价与费率。',
        commitHash: '75d4a0c',
      },
    ],
  },
]
