/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

// THIS FILE IS AUTOMATICALLY GENERATED FROM GIT LOG BEFORE EACH BUILD.
// DO NOT EDIT MANUALLY. CONVENTIONAL COMMITS ARE PARSED AUTOMATICALLY.

export interface CustomChangelogItem {
  tag: 'feat' | 'fix' | 'perf' | 'chore'
  titleEn: string
  titleZh: string
  descEn: string
  descZh: string
  commitHash?: string
}

export interface CustomReleaseGroup {
  version: string
  upstreamBase: string
  date: string
  items: CustomChangelogItem[]
}

export const CUSTOM_CHANGELOG_DATA: CustomReleaseGroup[] = [
  {
    version: 'v1.0.0-rc.41+custom',
    upstreamBase: 'v1.0.0-rc.41',
    date: '2026-10-06',
    items: [
    {
      "tag": "fix",
      "titleEn": "[changelog] 扩充日志提取深度并过滤内部构建提交",
      "titleZh": "[changelog] 扩充日志提取深度并过滤内部构建提交",
      "descEn": "Commit: 71d7813de (2026-10-06)",
      "descZh": "提交: 71d7813de · 2026-10-06",
      "commitHash": "71d7813de"
    },
    {
      "tag": "feat",
      "titleEn": "[mail] 增加大黄定制卡片式邮件模版与防拦截提示",
      "titleZh": "[mail] 增加大黄定制卡片式邮件模版与防拦截提示",
      "descEn": "Commit: 3b65989fb (2026-10-06)",
      "descZh": "提交: 3b65989fb · 2026-10-06",
      "commitHash": "3b65989fb"
    },
    {
      "tag": "feat",
      "titleEn": "[pricing] 配置 glm-5.3-flash 官方定价与阶梯费率",
      "titleZh": "[pricing] 配置 glm-5.3-flash 官方定价与阶梯费率",
      "descEn": "Commit: f879a9458 (2026-10-06)",
      "descZh": "提交: f879a9458 · 2026-10-06",
      "commitHash": "f879a9458"
    },
    {
      "tag": "chore",
      "titleEn": "[guidelines] 补充中文提交示例与文案要求",
      "titleZh": "[guidelines] 补充中文提交示例与文案要求",
      "descEn": "Commit: f50eecb70 (2026-10-03)",
      "descZh": "提交: f50eecb70 · 2026-10-03",
      "commitHash": "f50eecb70"
    },
    {
      "tag": "chore",
      "titleEn": "[guidelines] 统一 Commit 规范为客观克制中文并更新日志脚本",
      "titleZh": "[guidelines] 统一 Commit 规范为客观克制中文并更新日志脚本",
      "descEn": "Commit: 2e903d88b (2026-10-03)",
      "descZh": "提交: 2e903d88b · 2026-10-03",
      "commitHash": "2e903d88b"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] 自动化提取 Git 提交记录生成更新日志并制定提交规范",
      "titleZh": "[system-update] 自动化提取 Git 提交记录生成更新日志并制定提交规范",
      "descEn": "Commit: bfc05c5ae (2026-10-03)",
      "descZh": "提交: bfc05c5ae · 2026-10-03",
      "commitHash": "bfc05c5ae"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] 更新二开更新日志数据",
      "titleZh": "[system-update] 更新二开更新日志数据",
      "descEn": "Commit: 214280bb8 (2026-10-03)",
      "descZh": "提交: 214280bb8 · 2026-10-03",
      "commitHash": "214280bb8"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 接入 ZCode 与 Cherry Studio 官方配置截图及全屏查看",
      "titleZh": "[home] 接入 ZCode 与 Cherry Studio 官方配置截图及全屏查看",
      "descEn": "Commit: 57adf125d (2026-10-03)",
      "descZh": "提交: 57adf125d · 2026-10-03",
      "commitHash": "57adf125d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 使用 ZCode 官方图标并添加到首页支持应用列表",
      "titleZh": "[home] 使用 ZCode 官方图标并添加到首页支持应用列表",
      "descEn": "Commit: 953f17e7d (2026-10-03)",
      "descZh": "提交: 953f17e7d · 2026-10-03",
      "commitHash": "953f17e7d"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 添加 ZCode、Cherry Studio 与 DSH 界面配置图解",
      "titleZh": "[home] 添加 ZCode、Cherry Studio 与 DSH 界面配置图解",
      "descEn": "Commit: e942cd6d3 (2026-10-03)",
      "descZh": "提交: e942cd6d3 · 2026-10-03",
      "commitHash": "e942cd6d3"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 调整热门模型展示列表为 6 款主力模型及 3x2 网格",
      "titleZh": "[home] 调整热门模型展示列表为 6 款主力模型及 3x2 网格",
      "descEn": "Commit: 9d5f78a62 (2026-10-03)",
      "descZh": "提交: 9d5f78a62 · 2026-10-03",
      "commitHash": "9d5f78a62"
    },
    {
      "tag": "fix",
      "titleEn": "[home] 修正令牌路由为 /keys 并精简首页冗余模块",
      "titleZh": "[home] 修正令牌路由为 /keys 并精简首页冗余模块",
      "descEn": "Commit: d34c47f04 (2026-10-03)",
      "descZh": "提交: d34c47f04 · 2026-10-03",
      "commitHash": "d34c47f04"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 移除外部文档跳转，聚焦中转服务，自适应端点地址",
      "titleZh": "[home] 移除外部文档跳转，聚焦中转服务，自适应端点地址",
      "descEn": "Commit: cc28fbacb (2026-10-03)",
      "descZh": "提交: cc28fbacb · 2026-10-03",
      "commitHash": "cc28fbacb"
    },
    {
      "tag": "fix",
      "titleEn": "[home] 修复热门模型墙中 Grok 图标组件引用",
      "titleZh": "[home] 修复热门模型墙中 Grok 图标组件引用",
      "descEn": "Commit: d9775b769 (2026-10-03)",
      "descZh": "提交: d9775b769 · 2026-10-03",
      "commitHash": "d9775b769"
    },
    {
      "tag": "fix",
      "titleEn": "[i18n] 修复多语言字典命名空间层级并对齐平台可用模型",
      "titleZh": "[i18n] 修复多语言字典命名空间层级并对齐平台可用模型",
      "descEn": "Commit: 9f68e6549 (2026-10-03)",
      "descZh": "提交: 9f68e6549 · 2026-10-03",
      "commitHash": "9f68e6549"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 调整首页品牌文案与多语言配置",
      "titleZh": "[home] 调整首页品牌文案与多语言配置",
      "descEn": "Commit: f834d4577 (2026-10-03)",
      "descZh": "提交: f834d4577 · 2026-10-03",
      "commitHash": "f834d4577"
    },
    {
      "tag": "feat",
      "titleEn": "[home] 优化首页滚动流畅度，添加发卡网链接与客户端配置指南",
      "titleZh": "[home] 优化首页滚动流畅度，添加发卡网链接与客户端配置指南",
      "descEn": "Commit: 32a510784 (2026-10-03)",
      "descZh": "提交: 32a510784 · 2026-10-03",
      "commitHash": "32a510784"
    },
    {
      "tag": "fix",
      "titleEn": "[relayconvert] keep Responses custom tools on Claude and Gemini upstreams (#7636)",
      "titleZh": "[relayconvert] keep Responses custom tools on Claude and Gemini upstreams (#7636)",
      "descEn": "Commit: 1a4166d8e (2026-10-01)",
      "descZh": "提交: 1a4166d8e · 2026-10-01",
      "commitHash": "1a4166d8e"
    },
    {
      "tag": "fix",
      "titleEn": "[web] correct translations, chart ordering, and font loading (#7628)",
      "titleZh": "[web] correct translations, chart ordering, and font loading (#7628)",
      "descEn": "Commit: 56758edf9 (2026-09-30)",
      "descZh": "提交: 56758edf9 · 2026-09-30",
      "commitHash": "56758edf9"
    },
    {
      "tag": "feat",
      "titleEn": "[system-update] provide tabbed view for custom changelog and official upstream releases",
      "titleZh": "[system-update] provide tabbed view for custom changelog and official upstream releases",
      "descEn": "Commit: 08431501d (2026-09-30)",
      "descZh": "提交: 08431501d · 2026-09-30",
      "commitHash": "08431501d"
    },
    {
      "tag": "fix",
      "titleEn": "[i18n] keep cached zhTW/zhCN interface codes stable across page loads (#7139)",
      "titleZh": "[i18n] keep cached zhTW/zhCN interface codes stable across page loads (#7139)",
      "descEn": "Commit: 5fe8917be (2026-09-30)",
      "descZh": "提交: 5fe8917be · 2026-09-30",
      "commitHash": "5fe8917be"
    },
    {
      "tag": "fix",
      "titleEn": "[web] hide system settings from non-root admins (#7513)",
      "titleZh": "[web] hide system settings from non-root admins (#7513)",
      "descEn": "Commit: dfd3cd893 (2026-09-30)",
      "descZh": "提交: dfd3cd893 · 2026-09-30",
      "commitHash": "dfd3cd893"
    },
    {
      "tag": "fix",
      "titleEn": "[web] Add class to wrap the long strings at auto-disable status tooltip content in channel manage page (#7604)",
      "titleZh": "[web] Add class to wrap the long strings at auto-disable status tooltip content in channel manage page (#7604)",
      "descEn": "Commit: 811212067 (2026-09-30)",
      "descZh": "提交: 811212067 · 2026-09-30",
      "commitHash": "811212067"
    },
    {
      "tag": "fix",
      "titleEn": "use max_completion_tokens for gpt-6-sol and gpt-6-luna (#7559)",
      "titleZh": "use max_completion_tokens for gpt-6-sol and gpt-6-luna (#7559)",
      "descEn": "Commit: d0cb7347c (2026-09-30)",
      "descZh": "提交: d0cb7347c · 2026-09-30",
      "commitHash": "d0cb7347c"
    },
    {
      "tag": "fix",
      "titleEn": "isolate TLS configs across HTTP transports (#7627)",
      "titleZh": "isolate TLS configs across HTTP transports (#7627)",
      "descEn": "Commit: feefe09f2 (2026-09-30)",
      "descZh": "提交: feefe09f2 · 2026-09-30",
      "commitHash": "feefe09f2"
    },
    {
      "tag": "feat",
      "titleEn": "[web] add a refresh button to the channels table",
      "titleZh": "[web] add a refresh button to the channels table",
      "descEn": "Commit: 2035a82ae (2026-09-30)",
      "descZh": "提交: 2035a82ae · 2026-09-30",
      "commitHash": "2035a82ae"
    },
    {
      "tag": "feat",
      "titleEn": "[plugins] add Seedream 5.0 flash and price each Seedream model by its own tiers",
      "titleZh": "[plugins] add Seedream 5.0 flash and price each Seedream model by its own tiers",
      "descEn": "Commit: ae73ef8e2 (2026-09-30)",
      "descZh": "提交: ae73ef8e2 · 2026-09-30",
      "commitHash": "ae73ef8e2"
    },
    {
      "tag": "feat",
      "titleEn": "[auth] edit the name and permissions of an access token",
      "titleZh": "[auth] edit the name and permissions of an access token",
      "descEn": "Commit: 4924361ae (2026-09-30)",
      "descZh": "提交: 4924361ae · 2026-09-30",
      "commitHash": "4924361ae"
    },
    {
      "tag": "fix",
      "titleEn": "[auth] reject non-standard roles when creating a user",
      "titleZh": "[auth] reject non-standard roles when creating a user",
      "descEn": "Commit: 2506e1b98 (2026-09-30)",
      "descZh": "提交: 2506e1b98 · 2026-09-30",
      "commitHash": "2506e1b98"
    },
    {
      "tag": "chore",
      "titleEn": "build: derive custom versions from official tags",
      "titleZh": "build: derive custom versions from official tags",
      "descEn": "Commit: 56719a753 (2026-09-30)",
      "descZh": "提交: 56719a753 · 2026-09-30",
      "commitHash": "56719a753"
    }
],
  },
  {
    version: 'v1.0.0-rc.40+custom',
    upstreamBase: 'v1.0.0-rc.40',
    date: '2026-09-30',
    items: [
      {
        tag: 'feat',
        titleEn: 'Card shop recharge banner and redemption guide',
        titleZh: '钱包充值支持发卡网横幅与兑换引导',
        descEn: 'Added card shop recharge banner with direct access button and redemption guide.',
        descZh: '在钱包充值页增加发卡网自动充值横幅与直达购买按钮，增加卡密兑换引导胶囊。',
        commitHash: '75d4a0c',
      },
      {
        tag: 'feat',
        titleEn: 'Preset theme aligned to simple-large with 0.5 radius',
        titleZh: '系统出厂默认主题调整为简约大字体与 0.5 圆角',
        descEn: 'Set system default theme to simple-large, sans font, 0.5 radius (md), and auto dark mode.',
        descZh: '系统默认预设调整为超大字体简约、Sans 字体、0.5 圆角 (md) 及跟随系统深浅模式。',
        commitHash: '3fc6f2f',
      },
      {
        tag: 'feat',
        titleEn: 'Official tiered billing expressions and model pricing',
        titleZh: '模型官方阶梯计费与倍率对齐',
        descEn: 'Aligned model pricing expressions with official tiered rates for prompt caching reads and writes.',
        descZh: '对齐常用模型官方动态阶梯计费表达式，核算 Prompt Caching 读写差价与费率。',
        commitHash: '75d4a0c',
      },
    ],
  },
]
